version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  n_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: n_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    user: root
    volumes:
      - '/:/host:ro,rslave'

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/var/lib:/var/lib/grafana
      - ./grafana/etc:/etc/grafana
