global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9090', 'cadvisor:8080', 'n_exporter:9100']
